language: php

php:
    - 7.4
    - 8.0
    - 8.1

env:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

cache:
    directories:
        - ~/.composer/cache

install:
    - travis_retry composer update $DEPENDENCIES

script:
    - php vendor/bin/parallel-lint ./src ./tests
    - php vendor/bin/phpunit tests
    - php vendor/bin/ecs check --verbose ./src ./tests
